### ISSUE TITLE
Modifying items twice in one render

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-bunsen#50]
Ever since consuming `4.x` bunsen, I've been getting the following type of DEPRECATION warnings (lots of them):

```
DEPRECATION: You modified (mut errors) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
        at HANDLERS.(anonymous function) (http://localhost:4200/automation/assets/vendor.js:15791:7)
        at raiseOnDeprecation (http://localhost:4200/automation/assets/vendor.js:15699:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/automation/assets/vendor.js:15791:7)
        at invoke (http://localhost:4200/automation/assets/vendor.js:15807:7)
        at deprecate (http://localhost:4200/automation/assets/vendor.js:15760:32)
        at Object.deprecate (http://localhost:4200/automation/assets/vendor.js:25799:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/automation/assets/vendor.js:53062:26)
        at http://localhost:4200/automation/assets/vendor.js:23312:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/automation/assets/vendor.js:31712:11)
```
The *what* that was modified seems to be more than just `mut errors` it has also been:

 * `mut value`
 * `mut errorMessage`
 * `mut renderValue`
 
On a large, rather complex bunsen form, I get > 400 of these messages when it renders (with some default values), this makes finding any other messages in the midst of all that quite difficult. Not to mention the fact that bunsen appears to be doing something that is unreliable and will be removed :(

**Comment by sandersky** [comment]
Turned out to be an issue in a custom renderer.
